spring.application.name=ecommerce
server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/your_db
spring.datasource.username=your_user
spring.datasource.password=your_password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.data.elasticsearch.cluster-nodes=localhost:9200
spring.data.elasticsearch.cluster-name=elasticsearch

spring.redis.host=localhost
spring.redis.port=6379

keycloak.auth-server-url=http://localhost:8080/auth
keycloak.realm=yourRealm
keycloak.resource=yourClient
keycloak.credentials.secret=yourSecret
keycloak.bearer-only=true
keycloak.principal-attribute=preferred_username